package br.com.bomrastreio.api.correios.trace.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-09T19:17:11.453-02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "rastro", 
                  wsdlLocation = "https://webservice.correios.com.br/service/rastro/Rastro.wsdl",
                  targetNamespace = "http://resource.webservice.correios.com.br/") 
public class TraceWebServiceWrapper extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resource.webservice.correios.com.br/", "rastro");
    public final static QName ServicePort = new QName("http://resource.webservice.correios.com.br/", "ServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://webservice.correios.com.br/service/rastro/Rastro.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TraceWebServiceWrapper.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://webservice.correios.com.br/service/rastro/Rastro.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TraceWebServiceWrapper(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TraceWebServiceWrapper(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TraceWebServiceWrapper() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TraceWebServiceWrapper(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TraceWebServiceWrapper(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TraceWebServiceWrapper(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TraceWebService
     */
    @WebEndpoint(name = "ServicePort")
    public TraceWebService getServicePort() {
        return super.getPort(ServicePort, TraceWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TraceWebService
     */
    @WebEndpoint(name = "ServicePort")
    public TraceWebService getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, TraceWebService.class, features);
    }

}
